#!/bin/bash
set -ex
export MIX_ENV=test
mix deps.get
runuser postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'Postgres1234'\""
runuser postgres -c "psql -c \"UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1'\""
runuser postgres -c "psql -c \"DROP DATABASE template1\""
runuser postgres -c "psql -c \"CREATE DATABASE template1 WITH ENCODING = 'UTF8' TEMPLATE template0\""
runuser postgres -c "psql -c \"UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1'\""
mix test
