#!/bin/sh
if [ -z $BORS_WITHIN_DOCKER ]; then
  docker start borsng-dev || true
  docker exec -it mix clean || true
  docker rm -f borsng-dev
  docker rmi -f borsng/dev
else
  mix ecto.drop
  mix clean
fi
rm -rf _build
rm -rf deps
