#!/bin/sh
set -e
while [ ! -d script ] && [ `pwd` != / ]; do
  cd ..
done
if [ -z $BORS_WITHIN_DOCKER ]; then
  docker exec -it borsng-dev bash
else
  echo "This script is not necessary on the Janitor."
  exit 1
fi
