#!/bin/sh
set -e
while [ ! -d script ] && [ `pwd` != / ]; do
  cd ..
done
if [ ! -f ../janitor.json ]; then
  docker start borsng-dev
  exec docker exec -it borsng-dev "$0" "$@"
fi
mix phoenix.server
