#!/bin/sh
set -e
while [ ! -d script ] && [ `pwd` != / ]; do
  cd ..
done
if [ ! -f ../janitor.json ]; then
  docker rm -f borsng-dev
  docker build --tag borsng/dev --file script/Dockerfile
  docker create --name borsng-dev borsng/dev
  docker start borsng-dev
  exec docker exec -it borsng-dev "$0" "$@"
fi
mix do clean, deps.get, ecto.drop, ecto.create, ecto.migrate, build
npm install
