#!/bin/sh
set -e
while [ ! -d script ] && [ `pwd` != / ]; do
  cd ..
done
docker-compose -f script/docker-compose.yml build
docker-compose -f script/docker-compose.yml run --rm web mix deps.get
docker-compose -f script/docker-compose.yml run --rm web npm install
docker-compose -f script/docker-compose.yml run --rm web mix ecto.create
docker-compose -f script/docker-compose.yml run --rm web mix ecto.migrate
docker-compose -f script/docker-compose.yml run --rm web mix
