#!/bin/sh
set -e
while [ ! -d script ] && [ `pwd` != / ]; do
  cd ..
done
if [ -z $BORS_WITHIN_DOCKER ]; then
  docker start borsng-dev
  exec docker exec -it borsng-dev "$0" "$@"
fi
export MIX_ENV=test
mix do deps.get, test
export MIX_ENV=dev
mix dialyzer --halt-exit-status
