#!/bin/sh
set -e
while [ ! -d script ] && [ `pwd` != / ]; do
  cd ..
done
docker-compose -f script/docker-compose.yml run -e MIX_ENV=test --rm web mix test
if [ x$1 != x--fast ]; then
  docker-compose -f script/docker-compose.yml run --rm web mix dogma
  docker-compose -f script/docker-compose.yml run --rm web mix dialyzer --halt-exit-status
fi
